### ISSUE TITLE
SDK 2.26.1 memory increase high and freezing UI Screen

### ISSUE THREAD

**Issue by yeuem141289** [opentok/opentok-ios-sdk-samples#297] opened 2023-10-09 10:12 UTC
**Describe the bug**
In iphone 7 after call more three minutes memory measure increase high and cause UI Screen freezing. 
When i end call i lost 5-10s to have call back publisher(_ publisher: OTPublisherKit, streamDestroyed stream: OTStream). 
The delegate  func session(_ session: OTSession, streamDestroyed stream: OTStream) do not call

**To Reproduce**
- Call Video a few times more than 3 minutes

**Expected behavior**
- Memory not increase high fast and UI Screen not freezing

**Device (please compete the following information):**
- iOS SDK version: 2.26.1
- OS and version: Iphone 7 os 15.2, iphone X os 16.7 

**Additional context**
![Screenshot 2023-10-09 at 5 10 32 PM](https://github.com/opentok/opentok-ios-sdk-samples/assets/5528861/9a8a109b-6ecc-44fc-80f6-268b37d39c9e)

**Comment by yeuem141289** [comment] 2023-10-10 02:34
https://github.com/opentok/opentok-ios-sdk-samples/assets/5528861/f53d4fda-a93e-4f93-9473-93241751fc05

**Comment by v-kpheng** [comment] 2023-10-17 18:16
@yeuem141289, to confirm, you were able to reproduce this using one of our sample apps?  If so, which one?

**Comment by yeuem141289** [comment] 2023-10-18 06:04
I think i can fix this issue by set OTPublisher is singleton

**Comment by v-kpheng** [comment] 2023-10-25 17:43
@yeuem141289, nice troubleshooting 💪
Closing, since seems like you resolved it.

**Closed** 2023-10-25 17:42 UTC
